### ISSUE TITLE
Issue with tailwind intellisense

### ISSUE THREAD

**Issue by dannextlogic** [qp0kycHuk/tailwind-button-plugin#1]
Hi there and thanks for your plugin.

Unfortunately after installing the plugin and activating it within the tailwind config, tailwind intellisense is gone.
Any update regarding that would be awesome.

Thanks again.

**Comment by qp0kycHuk** [comment]
> Hi there and thanks for your plugin.
> 
> Unfortunately after installing the plugin and activating it within the tailwind config, tailwind intellisense is gone. Any update regarding that would be awesome.
> 
> Thanks again.

@dannextlogic 

Hi, can you send me git with this issue?

**Comment by qp0kycHuk** [comment]
> Hi there and thanks for your plugin.
> 
> Unfortunately after installing the plugin and activating it within the tailwind config, tailwind intellisense is gone. Any update regarding that would be awesome.
> 
> Thanks again.

@dannextlogic 

Or send output of intellisens

![image](https://github.com/qp0kycHuk/tailwind-button-plugin/assets/42573149/7f6b7cec-03ee-4688-ad9a-b3cdd23a9940)

**Comment by dannextlogic** [comment]
I was about to send you all that, but I've updated tailwind and postcss to latest and seems to have solved the issue for now. Will let you know of any issues, if any.

Thank you.

**Comment by qp0kycHuk** [comment]
@dannextlogic  I will be glad to receive feedback about this plugin
